import{useEffect,useState}from'react';import{Activity,Anchor,Bell,ChevronRight,Crosshair,Eye,Fuel,Hexagon,Layers3,LocateFixed,Map,Menu,Plane,Radio,Search,Settings,Shield,Swords,Target,Truck,Users,X}from'lucide-react';
type Unit={id:string;type:'air'|'naval'|'ground';name:string;kind:string;power:number;status:string;x:number;y:number};
const units:Unit[]=[{id:'viper',type:'air',name:'VIPER 2-1',kind:'F-35A STRIKE WING',power:84,status:'AIRBORNE',x:59,y:33},{id:'atlas',type:'ground',name:'ATLAS GROUP',kind:'ARMORED BRIGADE',power:92,status:'READY',x:39,y:59},{id:'trident',type:'naval',name:'TRIDENT CSG',kind:'CARRIER STRIKE GROUP',power:76,status:'PATROL',x:69,y:70},{id:'ghost',type:'ground',name:'GHOST 6',kind:'SPECIAL OPERATIONS',power:61,status:'CONCEALED',x:52,y:48},{id:'sentinel',type:'air',name:'SENTINEL',kind:'AWACS CONTROL',power:100,status:'ON STATION',x:29,y:30}];
const Icon=({type}:{type:Unit['type']})=>type==='air'?<Plane/>:type==='naval'?<Anchor/>:<Truck/>;
export default function App(){const[selected,setSelected]=useState(units[1]);const[tab,setTab]=useState('FORCES');const[modal,setModal]=useState(false);const[time,setTime]=useState(new Date());useEffect(()=>{let t=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(t)},[]);return <main>
<div className="map"><div className="terrain a"/><div className="terrain b"/><div className="grid"/><div className="front"/><label>NORTH ATLANTIC<small>OPERATIONAL ZONE</small></label>{units.map(u=><button className={`marker ${u.type} ${selected.id===u.id?'selected':''}`} style={{left:u.x+'%',top:u.y+'%'}} onClick={()=>setSelected(u)}><Icon type={u.type}/><b>{u.name}</b><small>{u.power}%</small></button>)}<code>48°51' N &nbsp; 02°21' E &nbsp; / &nbsp; THEATER 07</code></div>
<header><button className="brand"><Hexagon/><span><b>WARPATH</b><small>STRATEGIC COMMAND</small></span></button><div className="operation"><small>ACTIVE OPERATION</small><b>IRON HORIZON</b><em>DAY 014</em></div><div className="secure"><i/> GLOBAL LINK <b>SECURE</b></div><div className="clock"><small>UTC / ZULU</small><b>{time.toISOString().slice(11,19)}</b></div><button><Search/></button><button><Bell/></button><div className="profile"><i>CC</i><span><small>COMMANDER</small><b>CALLSIGN // RAVEN</b></span></div></header>
<nav><button className="active"><Map/></button><button><Crosshair/></button><button><Users/></button><button><Eye/></button><button><Radio/></button><span/><button><Settings/></button><button><Menu/></button></nav>
<aside className="left panel"><div className="tabs"><button className={tab==='FORCES'?'active':''} onClick={()=>setTab('FORCES')}>TASK FORCES</button><button className={tab==='INTEL'?'active':''} onClick={()=>setTab('INTEL')}>INTELLIGENCE</button></div>{tab==='FORCES'?<><div className="summary"><div><Plane/><b>2</b><small>AIR</small></div><div><Truck/><b>2</b><small>GROUND</small></div><div><Anchor/><b>1</b><small>NAVAL</small></div></div><Title text="DEPLOYED UNITS" meta="5 ACTIVE"/><div className="list">{units.map(u=><button className={selected.id===u.id?'active':''} onClick={()=>setSelected(u)}><i><Icon type={u.type}/></i><span><b>{u.name}</b><small>{u.kind}</small></span><em>{u.power}%</em><ChevronRight/></button>)}</div></>:<div className="intel">{['Hostile armor column detected near Sector Kilo.','Encrypted transmission intercepted offshore.','Trident resupply convoy entered grid.','Storm front advancing from northwest.'].map((x,i)=><article><time>18:{42-i*7}Z</time><b>{i?'SIGINT':'HIGH'}</b><p>{x}</p></article>)}</div>}<button className="all">VIEW ALL ASSETS <ChevronRight/></button></aside>
<section className="mission panel"><div><span><Target/> PRIMARY OBJECTIVE</span><b>PHASE II</b></div><h2>SECURE THE STRAIT</h2><p>Establish air superiority and control maritime access before hostile reinforcements arrive.</p><aside><small>OPERATION PROGRESS</small><b>64%</b></aside><progress value="64" max="100"/><footer><span><small>TIME REMAINING</small><b>18:42:16</b></span><span><small>THREAT LEVEL</small><b>ELEVATED</b></span></footer></section>
<aside className="right panel"><div className="hero"><i><Icon type={selected.type}/></i><span><small>SELECTED UNIT</small><h2>{selected.name}</h2><p>{selected.kind}</p></span><X/></div><div className="ready"><span><small>COMBAT READINESS</small><b>{selected.power}%</b></span><i style={{'--score':selected.power*3.6+'deg'} as React.CSSProperties}><strong>{selected.status}</strong></i></div><div className="metrics"><Metric icon={<Activity/>} a="STRENGTH" b={selected.power+'%'}/><Metric icon={<Fuel/>} a="SUPPLY" b="78%"/><Metric icon={<Shield/>} a="DEFENSE" b="86%"/><Metric icon={<LocateFixed/>} a="RANGE" b="1,240 KM"/></div><Title text="ACTIVE ORDERS" meta="01"/><div className="order"><i/><span><b>HOLD POSITION</b><small>GRID 07-F // SINCE 16:20Z</small></span></div><button className="command" onClick={()=>setModal(true)}><Swords/> ISSUE COMMAND</button><button className="quick" onClick={()=>setModal(true)}>QUICK ENGAGEMENT <ChevronRight/></button></aside>
<div className="controls"><button><Layers3/></button><button><LocateFixed/></button></div><div className="status"><span>● FRIENDLY CONTROL</span><span>● HOSTILE ACTIVITY</span><span>● CONTESTED ZONE</span><b>MAP DATA // SATCOM 4</b><small>UPDATED 12 SEC AGO</small></div>
{modal&&<div className="backdrop" onClick={()=>setModal(false)}><section className="dialog panel" onClick={e=>e.stopPropagation()}><button onClick={()=>setModal(false)}><X/></button><small>FIELD COMMAND // {selected.name}</small><h1>ENGAGEMENT DIRECTIVE</h1><p>Resolve this encounter using current force readiness and tactical advantage.</p><div><span><b>{selected.power}%</b><small>VICTORY PROJECTION</small></span><ChevronRight/><span><b>MODERATE</b><small>ESTIMATED LOSSES</small></span></div><button className="execute" onClick={()=>setModal(false)}><Swords/> AUTHORIZE QUICK FIGHT</button></section></div>}</main>}
function Title({text,meta}:{text:string;meta:string}){return <div className="title"><span>{text}</span><small>{meta}</small></div>}function Metric({icon,a,b}:{icon:React.ReactNode;a:string;b:string}){return <div>{icon}<small>{a}</small><b>{b}</b></div>}
